name: .NET Core

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build .\XiangJiang.Infrastructure.Windows.UIA Dockerfile.msbuild --tag auycro/msbuild .
        #run: docker build . --file Dockerfile --tag auycro/dotnet:$(date +%s)
      - name: Run the Docker image
        run: docker run --rm auycro/msbuild --version
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Install Nuget
        run: | 
             $sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
             $targetNugetExe = "nuget.exe"
             Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe
      - name: create package
        run: .\nuget pack .\XiangJiang.Infrastructure.Windows.UIA.csproj -Prop Configuration=Release -IncludeReferencedProjects
      - name: Push generated package to GitHub registry
        run: |
          .\nuget push .\XiangJiang.Infrastructure.Windows.UIA\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbols
